accelerate launch train_svd_lora.py \
    --pretrained_model_name_or_path=/path/to/stable-video-diffusion-img2vid-xt-1-1 \
    --per_gpu_batch_size=1 --gradient_accumulation_steps=1 \
    --max_train_steps=4000 \
    --width=1024 \
    --height=576 \
    --checkpointing_steps=1000 --checkpoints_total_limit=3 \
    --learning_rate=1e-5 --lr_warmup_steps=0 \
    --seed=123 \
    --mixed_precision="fp16" \
    --validation_steps=200 \
    --rank 16 \
    --gradient_checkpointing \
    --output_dir ./outputs \